version: 0.0
os: linux
files:
   - source: ./
     destination: /home/ubuntu/infynity-cicd/infynity-ui
hooks:
   BeforeInstall:
      - location: scripts/delete_old_files.sh
        timeout: 300
        runas: root
   ApplicationStart:
      - location: scripts/start_server.sh
        timeout: 300
        runas: root
