version: 0.2

env:
   variables:
      NODE_ENV: dev

phases:
   install:
      runtime-versions:
         nodejs: 20.11
      commands:
         - echo ---------- Installing dependencies ----------
         - npm i -g yarn
         - yarn

   build:
      commands:
         - echo ---------- Running Build ----------
         - yarn build:dev

   post_build:
      commands:
         - echo ---------- Build Completed ----------
         - echo ---------- Preparing artifacts for deployment ----------
         - pwd
         - ls

artifacts:
   files:
      - '**/*'
   discard-paths: no

cache:
   paths:
      - 'node_modules/**/*'
